"""Test cases for plugin output."""

import os
import unittest

from azul_smart_string_filter.lib import SmartStringFilter


MODEL_TYPE = "combined"
MINIMUM_ACCURACY_PERCENT = 95.0


class TestAIModel(unittest.TestCase):
    def test_ai_model_output_windows(self):
        """Measure the model against the hardcoded GOOD/BAD ground truth."""
        base_file_dir = os.path.join(os.path.dirname(__file__), "data")
        file_path = os.path.join(base_file_dir, "strings_list.txt")
        string_list = []
        with open(file_path, "r", encoding="utf-8", errors="ignore") as file:
            for line in file:
                string = line.strip()
                string_list.append(string)

        string_filter = SmartStringFilter()
        predictions = string_filter.find_legible_strings(
            string_list,
            model_type=MODEL_TYPE,
        )
        self.assertEqual(len(predictions), len(string_list))

        # Hardcoded ground truth. True means GOOD and False means BAD.
        expected_results: list[tuple[str, bool]] = [
                ("!This program cannot be run in DOS mode.", True),
                (".text", True),
                ("`.rsrc", True),
                ("@.reloc", True),
                ("X )UU", False),
                ("X )UU", False),
                ("X )UU", False),
                ("*.(J", False),
                ("+*.sL", False),
                ("*.sb", False),
                ("&rCP", False),
                ("*nr4V", False),
                ("*^~\\", False),
                ("*rd_", False),
                ("*.sc", False),
                ("*.sm", False),
                ("*.s1", False),
                ("*.sn", False),
                ("*.rwk", False),
                ("+ws8", False),
                (",O~", False),
                ("*\trk", False),
                ("%-$&", False),
                ("%r{!", False),
                ('%rs"', False),
                ("%rs%", False),
                ("%rk(", False),
                ("%rS)", False),
                ("%r;*", False),
                ("%r3+", False),
                ("%r+,", False),
                ("%r#-", False),
                ("%ro2", False),
                ("%r_3", False),
                ("%ro4", False),
                ("%r3<", False),
                ("%rK=", False),
                ("%rC>", False),
                ("%r;?", False),
                ("%rC@", False),
                ("%rKA", False),
                (",;\tr", False),
                ("%rKC", False),
                (".rjM", False),
                (",*rqP", False),
                ("rjM", False),
                ("&rCP", False),
                ("&rCP", False),
                ("&rCP", False),
                ("&rCP", False),
                ("r3R", False),
                ("+rvU", False),
                ('%r"V', False),
                ("%r.W", False),
                ("%r%\\", False),
                ("%r?\\", False),
                ("%ra\\", False),
                ("%rs\\", False),
                ("%rD`", False),
                ("%r^`", False),
                ("%r0a", False),
                ("%rZa", False),
                ("%rla", False),
                ("%r$b", False),
                ("%r>b", False),
                ("%rXb", False),
                ("%rzb", False),
                ("+T\t-", False),
                ("+:\t,7", False),
                (",\ts5", False),
                ("\\r7d", False),
                ("i([", False),
                ("Xi(-", False),
                ("YjX!", False),
                ("jXi(&", False),
                ("jXi(&", False),
                ("jXi(&", False),
                ("jXi(&", False),
                ("Xi(-", False),
                ("Ymn}", False),
                ("-\t~n", False),
                ("&rd_", False),
                ("+rkf", False),
                ("KDBM(", False),
                ("&r}i", False),
                ("&ro", False),
                ("&r#j", False),
                ("ZX+", False),
                ("BSJB", False),
                ("v4.0.30319", True),
                ("#Strings", True),
                ("#GUID", True),
                ("#Blob", True),
                ("@%L%", False),
                ("p&L%", False),
                ("/F2\tV", False),
                ("8F2\tV", False),
                ("@F2\tV", False),
                ("LF2\t!", False),
                ("=M2", False),
                ("p2G", False),
                ("@3b", False),
                ("P3g", False),
                ("_Ha", False),
                ("!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHI", True),
                ("JKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~", True),
                ("J-h-", False),
                ("BNl", False),
                (
                    "#\"%$&$(')'+*,*32426575:9;9>=?=@=A=B=C=D=E=IHJHKHLHMHNHOHPHQHRHSHTHUHVHYXZX[X\\X]Xa`cbdbebfbgbihjhlkmknkokpkqkrkskutvtwtyx",
                    False,
                ),
                ("mscorlib", True),
                ("Object", True),
                ("System", True),
                ("Attribute", True),
                ("List`1", True),
                ("System.Collections.Generic", True),
                ("Func`2", True),
                ("System.Core", True),
                ("IGrouping`2", True),
                ("System.Linq", True),
                ("Thread", True),
                ("System.Threading", True),
                ("Action`1", True),
                ("IEnumerable`1", True),
                ("IEnumerable", True),
                ("System.Collections", True),
                ("IEnumerator`1", True),
                ("IDisposable", True),
                ("IEnumerator", True),
                ("ValueType", True),
                ("KeyValuePair`2", True),
                ("Func`1", True),
                ("MulticastDelegate", True),
                ("IAsyncResult", True),
                ("AsyncCallback", True),
                ("RSAParameters", True),
                ("System.Security.Cryptography", True),
                ("Process", True),
                ("System.Diagnostics", True),
                ("CultureInfo", True),
                ("System.Globalization", True),
                ("System.Windows.Forms", True),
                ("InputLanguage", True),
                ("Mutex", True),
                ("Dictionary`2", True),
                ("Match", True),
                ("System.Text.RegularExpressions", True),
                ("Func`3", True),
                ("Enum", True),
                ("StringBuilder", True),
                ("System.Text", True),
                ("FILETIME", True),
                ("System.Runtime.InteropServices.ComTypes", True),
                ("Random", True),
                ("Type", True),
                ("Stream", True),
                ("System.IO", True),
                ("FileAccess", True),
                ("Encoding", True),
                ("DateTime", True),
                ("HMAC", False),
                ("CompilationRelaxationsAttribute", True),
                ("System.Runtime.CompilerServices", True),
                ("RuntimeCompatibilityAttribute", True),
                ("DebuggableAttribute", True),
                ("DebuggingModes", True),
                ("AssemblyTitleAttribute", True),
                ("System.Reflection", True),
                ("AssemblyDescriptionAttribute", True),
                ("AssemblyConfigurationAttribute", True),
                ("AssemblyCompanyAttribute", True),
                ("AssemblyProductAttribute", True),
                ("AssemblyCopyrightAttribute", True),
                ("AssemblyTrademarkAttribute", True),
                ("ComVisibleAttribute", True),
                ("System.Runtime.InteropServices", True),
                ("GuidAttribute", True),
                ("AssemblyFileVersionAttribute", True),
                ("TargetFrameworkAttribute", True),
                ("System.Runtime.Versioning", True),
                ("Delegate", True),
                ("CompilerGeneratedAttribute", True),
                ("DebuggerBrowsableAttribute", True),
                ("DebuggerBrowsableState", True),
                ("DebuggerHiddenAttribute", True),
                ("AttributeUsageAttribute", True),
                ("AttributeTargets", True),
                ("ParamArrayAttribute", True),
                ("FlagsAttribute", True),
                ("EqualityComparer`1", True),
                ("String", True),
                ("IFormatProvider", True),
                ("MemoryStream", True),
                ("Enumerable", True),
                ("ThreadStart", True),
                ("NotSupportedException", True),
                ("Stopwatch", True),
                ("Environment", True),
                ("SpecialFolder", True),
                ("Enumerator", True),
                ("Path", True),
                ("Directory", True),
                ("File", True),
                ("Char", True),
                ("Convert", True),
                ("Regex", True),
                ("Byte", True),
                ("Array", True),
                ("Int32", True),
                ("NumberStyles", True),
                ("UInt64", True),
                ("Boolean", True),
                ("FileInfo", True),
                ("StringSplitOptions", True),
                ("Math", True),
                ("Double", True),
                ("Assembly", True),
                ("System.Drawing", True),
                ("Rectangle", True),
                ("Screen", True),
                ("WebClient", True),
                ("System.Net", True),
                ("System.Management", True),
                ("ManagementObjectCollection", True),
                ("ManagementObjectEnumerator", True),
                ("ManagementObjectSearcher", True),
                ("ManagementBaseObject", True),
                ("NetworkInterface", True),
                ("System.Net.NetworkInformation", True),
                ("OperationalStatus", True),
                ("PhysicalAddress", True),
                ("HashAlgorithm", True),
                ("Registry", True),
                ("Microsoft.Win32", True),
                ("Bitmap", True),
                ("Graphics", True),
                ("IntPtr", True),
                ("Image", True),
                ("Size", True),
                ("ImageFormat", True),
                ("System.Drawing.Imaging", True),
                ("FileSystemInfo", True),
                ("HttpWebRequest", True),
                ("StreamWriter", True),
                ("ServicePointManager", True),
                ("SecurityProtocolType", True),
                ("WebRequest", True),
                ("Int64", True),
                ("TextWriter", True),
                ("WebResponse", True),
                ("TcpClient", True),
                ("System.Net.Sockets", True),
                ("NetworkStream", True),
                ("BinaryWriter", True),
                ("BitConverter", True),
                ("System.Xml", True),
                ("XmlSerializer", True),
                ("System.Xml.Serialization", True),
                ("XmlReader", True),
                ("RuntimeTypeHandle", True),
                ("RSACryptoServiceProvider", True),
                ("CryptoStream", True),
                ("SymmetricAlgorithm", True),
                ("ICryptoTransform", True),
                ("CryptoStreamMode", True),
                ("Buffer", True),
                ("InputLanguageCollection", True),
                ("Predicate`1", True),
                ("MatchCollection", True),
                ("Capture", True),
                ("UnauthorizedAccessException", True),
                ("PathTooLongException", True),
                ("DirectoryNotFoundException", True),
                ("Marshal", True),
                ("Win32Exception", True),
                ("System.ComponentModel", True),
                ("Guid", True),
                ("ArgumentException", True),
                ("ManagementObject", True),
                ("UInt32", True),
                ("StringComparison", True),
                ("Activator", True),
                ("RuntimeHelpers", True),
                ("RuntimeFieldHandle", True),
                ("InvalidOperationException", True),
                ("DeflateStream", True),
                ("System.IO.Compression", True),
                ("CompressionMode", True),
                ("HMACSHA1", True),
                ("SHA1CryptoServiceProvider", True),
                ("SHA1Managed", True),
                ("TripleDESCryptoServiceProvider", True),
                ("StreamReader", True),
                ("CipherMode", True),
                ("PaddingMode", True),
                ("TextReader", True),
                ("HMACSHA256", True),
                ("AesManaged", True),
                ("ArgumentNullException", True),
                ("KeyedHashAlgorithm", True),
                ("BinaryReader", True),
                ("Dispose", True),
                ("MoveNext", True),
                ("get_Current", True),
                ("Reset", True),
                ("GetEnumerator", True),
                (".ctor", True),
                ("<file>i__Field", True),
                ("<data>i__Field", True),
                ("get_Default", True),
                ("Equals", True),
                ("GetHashCode", True),
                ("ToString", True),
                ("Format", True),
                ("<<>h__TransparentIdentifier0>i__Field", True),
                ("<match>i__Field", True),
                ("<<>h__TransparentIdentifier1>i__Field", True),
                ("<encrypted>i__Field", True),
                ("GroupBy", True),
                ("Select", True),
                ("ToList", True),
                ("ForEach", True),
                ("ToArray", True),
                ("Start", True),
                ("Join", True),
                ("get_CurrentThread", True),
                ("get_ManagedThreadId", True),
                ("get_Count", True),
                ("get_UTF8", True),
                ("GetBytes", True),
                ("Distinct", True),
                ("get_Now", True),
                ("Collect", True),
                ("WaitForPendingFinalizers", True),
                ("GetFolderPath", True),
                ("Stop", True),
                ("Concat", True),
                ("Replace", True),
                ("get_Value", True),
                ("Combine", True),
                ("Exists", True),
                ("GetFiles", True),
                ("get_Key", True),
                ("ReadAllBytes", True),
                ("Split", True),
                ("Last", True),
                ("AddRange", True),
                ("Empty", True),
                ("op_Equality", True),
                ("get_Length", True),
                ("FromBase64String", True),
                ("get_Item", True),
                ("GetString", True),
                ("op_Inequality", True),
                ("Contains", True),
                ("GetEncoding", True),
                ("StartsWith", True),
                ("Copy", True),
                ("Where", True),
                ("FirstOrDefault", True),
                ("Substring", True),
                ("Parse", True),
                ("get_ASCII", True),
                ("GetDirectories", True),
                ("Invoke", True),
                ("ToUpper", True),
                ("ReadAllText", True),
                ("First", True),
                ("GetFileName", True),
                ("TakeWhile", True),
                ("SelectMany", True),
                ("get_UserName", True),
                ("Remove", True),
                ("get_MachineName", True),
                ("get_Is64BitOperatingSystem", True),
                ("Round", True),
                ("GetEntryAssembly", True),
                ("get_Location", True),
                ("get_PrimaryScreen", True),
                ("get_Bounds", True),
                ("get_Width", True),
                ("get_Height", True),
                ("DownloadString", True),
                ("GetAllNetworkInterfaces", True),
                ("get_OperationalStatus", True),
                ("GetPhysicalAddress", True),
                ("GetAddressBytes", True),
                ("ToDouble", True),
                ("Append", True),
                ("Create", True),
                ("ComputeHash", True),
                ("ToLower", True),
                ("GetValue", True),
                ("Zero", True),
                ("FromImage", True),
                ("get_Size", True),
                ("CopyFromScreen", True),
                ("get_Png", True),
                ("Save", True),
                ("get_DirectoryName", True),
                ("get_Name", True),
                ("EndsWith", True),
                ("set_DefaultConnectionLimit", True),
                ("set_Expect100Continue", True),
                ("set_SecurityProtocol", True),
                ("set_Method", True),
                ("set_Timeout", True),
                ("set_UserAgent", True),
                ("get_Ticks", True),
                ("set_ContentType", True),
                ("WriteLine", True),
                ("Flush", True),
                ("CopyTo", True),
                ("Close", True),
                ("set_ContentLength", True),
                ("set_Position", True),
                ("GetRequestStream", True),
                ("GetResponse", True),
                ("ToInt32", True),
                ("Connect", True),
                ("GetStream", True),
                ("Write", True),
                ("GetTypeFromHandle", True),
                ("Deserialize", True),
                ("ImportParameters", True),
                ("GenerateKey", True),
                ("get_IV", True),
                ("CreateEncryptor", True),
                ("FlushFinalBlock", True),
                ("Encrypt", True),
                ("BlockCopy", True),
                ("GetProcesses", True),
                ("Kill", True),
                ("get_ProcessName", True),
                ("FailFast", True),
                ("get_InstalledInputLanguages", True),
                ("Cast", True),
                ("get_Culture", True),
                ("IsNullOrEmpty", True),
                ("Skip", True),
                ("Take", True),
                ("get_data", True),
                ("Matches", True),
                ("get_match", True),
                ("get_encrypted", True),
                ("GetLastWin32Error", True),
                ("GetDelegateForFunctionPointer", True),
                ("StringToHGlobalUni", True),
                ("FreeHGlobal", True),
                ("PtrToStringUni", True),
                ("get_Chars", True),
                ("TrimStart", True),
                ("TrimEnd", True),
                ("Trim", True),
                ("NewGuid", True),
                ("GetProcessById", True),
                ("GetLogicalDrives", True),
                ("Compare", True),
                ("IndexOf", True),
                ("TryGetValue", True),
                ("LastIndexOf", True),
                ("AllocHGlobal", True),
                ("ToInt64", True),
                ("SizeOf", True),
                ("ReadInt64", True),
                ("ReadInt32", True),
                ("op_Explicit", True),
                ("PtrToStructure", True),
                ("get_Id", True),
                ("get_HandleCount", True),
                ("Next", True),
                ("NextDouble", True),
                ("GetAssembly", True),
                ("GetTypes", True),
                ("<>9__0_0", False),
                ("<GetInheritedClasses>b__0_0", True),
                ("<>9__0_1", False),
                ("<GetInheritedClasses>b__0_1", True),
                ("get_IsClass", True),
                ("get_IsAbstract", True),
                ("IsSubclassOf", True),
                ("CreateInstance", True),
                ("InitializeArray", True),
                ("Sleep", True),
                ("Resize", True),
                ("get_Unicode", True),
                ("get_BigEndianUnicode", True),
                ("get_Position", True),
                ("get_CanSeek", True),
                ("Read", True),
                ("SetLength", True),
                ("get_Second", True),
                ("get_Minute", True),
                ("get_Hour", True),
                ("get_Day", True),
                ("get_Month", True),
                ("get_Year", True),
                ("ToFileTime", True),
                ("SuppressFinalize", True),
                ("get_InvariantCulture", True),
                ("set_Key", True),
                ("set_IV", True),
                ("set_Mode", True),
                ("set_Padding", True),
                ("CreateDecryptor", True),
                ("ReadToEnd", True),
                ("set_BlockSize", True),
                ("set_KeySize", True),
                ("TransformFinalBlock", True),
                ("get_HashSize", True),
                ("IsLittleEndian", True),
                ("AppendLine", True),
                ("AppendFormat", True),
                ("get_BaseStream", True),
                ("ReadByte", True),
                ("Sort", True),
                ("IsNullOrWhiteSpace", True),
                ("Reverse", True),
                ("Hello", True),
                ("<Module>", True),
                ("<>f__AnonymousType0`2", True),
                ("<file>j__TPar", True),
                ("<data>j__TPar", True),
                ("get_file", True),
                ("file", True),
                ("data", True),
                ("value", True),
                ("<>f__AnonymousType1`2", True),
                ("<<>h__TransparentIdentifier0>j__TPar", True),
                ("<match>j__TPar", True),
                ("get_<>h__TransparentIdentifier0", True),
                ("<>h__TransparentIdentifier0", True),
                ("match", True),
                ("<>f__AnonymousType2`2", True),
                ("<<>h__TransparentIdentifier1>j__TPar", True),
                ("<encrypted>j__TPar", True),
                ("get_<>h__TransparentIdentifier1", True),
                ("<>h__TransparentIdentifier1", True),
                ("encrypted", True),
                ("Icipucudovy", True),
                ("Lyjygap", True),
                ("Atygimokoby", True),
                ("Zetimov", True),
                ("Pusaxelimegynyfer", True),
                ("int_0", True),
                ("Jodohejybum", True),
                ("Rujecor", True),
                ("Xujijogacogijegag", True),
                ("Ixytegykenatejohi", True),
                ("Manoxovipizakikul", True),
                ("Goxifadaluvuzyxup", True),
                ("Cybekijuhirevabec", True),
                ("Oxalidupamycasope", True),
                ("Agybotiluzeruvufe", True),
                ("Fokefirigejalokif", True),
                ("Kadiruhucygudukec", True),
                ("Dysyvodijitijemuv", True),
                ("Juxozihyfifopelih", True),
                (".cctor", True),
                ("Onepogonejy", True),
                ("Hizexecovinaj", True),
                ("<>9__0_3", False),
                ("<>9__0_4", False),
                ("<>9__0_5", False),
                ("<Main>b__0_0", True),
                ("<Main>b__0_1", True),
                ("<Main>b__0_3", True),
                ("service", True),
                ("<Main>b__0_4", True),
                ("<Main>b__0_5", True),
                ("<>c__DisplayClass0_0", True),
                ("Karykoxumymufojec", True),
                ("<>9__6", False),
                ("<Main>b__2", True),
                ("<Main>b__6", True),
                ("Ekubikylaco", True),
                ("Udyrovepusepaducy", True),
                ("Kelomilizagapulyn", True),
                ("Somucagozaragynep", True),
                ("Fekocegumonynodyf", True),
                ("Xogigymisuxelidis", True),
                ("Vanemelocymabitag", True),
                ("Vubodumivedavexyb", True),
                ("Vudyzosovusolegan", True),
                ("Fezysalelydedehuh", True),
                ("Ysytivorusevypupy", True),
                ("Axyladukunofobugu", True),
                ("Ejinatyxukebu", True),
                ("<Finalize>d__11", True),
                ("<>1__state", True),
                ("<>2__current", True),
                ("<>l__initialThreadId", True),
                ("System.IDisposable.Dispose", True),
                ("System.Collections.Generic.IEnumerator<Hadytus.Enyroxobuzi>.get_Current", True),
                ("System.Collections.IEnumerator.Reset", True),
                ("System.Collections.IEnumerator.get_Current", True),
                ("System.Collections.Generic.IEnumerable<Phemedrone.Classes.LogRecord>.GetEnumerator", True),
                ("System.Collections.IEnumerable.GetEnumerator", True),
                ("System.Collections.Generic.IEnumerator<Hadytus.Enyroxobuzi>.Current", True),
                ("System.Collections.IEnumerator.Current", True),
                ("Erusugyhydi", True),
                ("Ronesagurifimalov", True),
                ("get_Ulasujybigyny", True),
                ("Remopepulagaf", True),
                ("Bihoxoruputit", True),
                ("Febudacefazesitod", True),
                ("Xozupuryzyfepakys", True),
                ("Ulasujybigyny", True),
                ("Kyjaresogez", True),
                ("Xuzujas", True),
                ("Erebapotyneva", True),
                ("Upimigizajosazosu", True),
                ("Ovegicemunole", True),
                ("Ezezurumamimuroci", True),
                ("<>c__DisplayClass3_0", True),
                ("Oxapurimysujicevy", True),
                ("<ParseDatWallets>b__0", True),
                ("<>c__DisplayClass4_0", True),
                ("Zezimusiroxebaxuf", True),
                ("<ParseColdWallets>b__0", True),
                ("Uhynuxygidi", True),
                ("Lyhabusahohicufyb", True),
                ("Dazamycunijok", True),
                ("Ujofafycobijubova", True),
                ("oxidycytypecera_0", True),
                ("Oxidycytypecera", True),
                ("Vocidudujyhaxicat", True),
                ("<>c__DisplayClass3_1", True),
                ("Najakevumapaxuvyk", True),
                ("<Collect>b__1", True),
                ("Ajydoceredy", True),
                ("Bizuhufilovix", True),
                ("Vokalesibemijunip", True),
                ("Uxagixyxidecetyzo", True),
                ("Cabyhojudyjivazep", True),
                ("Ajifigahidumotuje", True),
                ("Luhuvedidomov", True),
                ("Ecabycenujecosiji", True),
                ("Ixemebumezufy", True),
                ("Ycaxykazogejatili", True),
                ("GetBrowserName", True),
                ("root", True),
                ("location", True),
                ("ListProfiles", True),
                ("rootLocation", True),
                ("<>9__2_0", False),
                ("<>9__2_1", False),
                ("<>9__2_2", False),
                ("<>9__5_1", False),
                ("<>9__5_2", False),
                ("<>9__5_3", False),
                ("<>9__5_4", False),
                ("<>9__5_5", False),
                ("<>9__5_6", False),
                ("<Collect>b__2_0", True),
                ("directory", True),
                ("<Collect>b__2_1", True),
                ("<Collect>b__2_2", True),
                ("<Key3Database>b__5_1", True),
                ("<Key3Database>b__5_2", True),
                ("<Key3Database>b__5_3", True),
                ("<Key3Database>b__5_4", True),
                ("<Key3Database>b__5_5", True),
                ("<Key3Database>b__5_6", True),
                ("Odeborekihysuteda", True),
                ("<ParsePasswords>b__0", True),
                ("<>c__DisplayClass5_0", True),
                ("Zekotipikulikibum", True),
                ("<Key3Database>b__0", True),
                ("Forycizukas", True),
                ("Rulexybekijuh", True),
                ("Obudymobasonerose", True),
                ("Dezaxemepujulugop", True),
                ("Cukexosokanan", True),
                ("Zokigykijysazahik", True),
                ("Sumolobizyzikubek", True),
                ("Ejeryjumimuhupahe", True),
                ("<>9__2_3", False),
                ("<Collect>b__2_3", True),
                ("<>c__DisplayClass2_0", True),
                ("browserRoot", True),
                ("masterKey", True),
                ("browserName", True),
                ("browserVersion", True),
                ("<>9__2", False),
                ("<Collect>b__2", True),
                ("<>c__DisplayClass2_1", True),
                ("profileName", True),
                ("CS$<>8__locals1", True),
                ("<Collect>b__4", True),
                ("<Collect>b__5", True),
                ("<Collect>b__6", True),
                ("<>c__DisplayClass6_0", True),
                ("Fugekujybymugojyk", True),
                ("<ParseExtensions>b__0", True),
                ("Vyresipyfes", True),
                ("Ubaxufepyba", True),
                ("totalSize", True),
                ("<>9__0", False),
                ("<Collect>b__0", True),
                ("pattern", True),
                ("<>9__1", False),
                ("<>c__DisplayClass2_2", True),
                ("Umivononyxu", True),
                ("Pusotelorutivenoj", True),
                ("Hixygyvuzofen", True),
                ("Asymykuguzito", True),
                ("Fymisenohiced", True),
                ("Esohiboxejydo", True),
                ("Gekecisuvarax", True),
                ("Bujehevinopif", True),
                ("Omagopimydyfe", True),
                ("Cizytifiholom", True),
                ("Upimyrejidula", True),
                ("Taxibymyrifek", True),
                ("Jocyxafyguzid", True),
                ("Fykesukosatit", True),
                ("<>9__9_0", False),
                ("<GetWindowsVersion>b__9_0", True),
                ("Tajutoxetux", True),
                ("Edyxatosexuvaza", True),
                ("object", True),
                ("method", True),
                ("hWnd", True),
                ("BeginInvoke", True),
                ("callback", True),
                ("EndInvoke", True),
                ("result", True),
                ("Urosazanopoxyre", True),
                ("nIndex", True),
                ("Izigycohosu", True),
                ("Tipucejozos", True),
                ("Zesifafejahun", True),
                ("Ivudateceholyrifu", True),
                ("okytuzegytejeci_0", True),
                ("Okytuzegytejeci", True),
                ("Unobitehofoxybesi", True),
                ("Ynufahatyjysurele", True),
                ("Usitajyterapucavi", True),
                ("Onozutedive", True),
                ("Fukezod", True),
                ("Nadalijyvix", True),
                ("Kavipyl", True),
                ("Send", True),
                ("Avetamilexo", True),
                ("Xepyrilavidagybik", True),
                ("args", True),
                ("Eninerymajinu", True),
                ("Pumopotemunetimid", True),
                ("Gemifofofitevonab", True),
                ("Ilutabozyfyruhopa", True),
                ("Umekyjamitepykoxo", True),
                ("Sajyjepekopaxybal", True),
                ("Upoxifibuto", True),
                ("Cokunarobakeg", True),
                ("Ajysigirymytytuge", True),
                ("Odytynefipudicodo", True),
                ("Gotegojihafydebit", True),
                ("Rebaxegoheryvenix", True),
                ("Oponejigapa", True),
                ("token", True),
                ("chatId", True),
                ("publicKey", True),
                ("Ihigyhykenizu", True),
                ("Ofumijutydahumaxy", True),
                ("Talimupysymej", True),
                ("Gylyramaxazipetex", True),
                ("Ibaxohuxupamuceza", True),
                ("Ezokytobygi", True),
                ("Ugilage", True),
                ("Vysarokigysek", True),
                ("<KillDebuggers>b__0_1", True),
                ("process", True),
                ("Ihohyvuhugunojepy", True),
                ("<KillDebuggers>b__0", True),
                ("Ybumelezyby", True),
                ("Ajydyfacolypo", True),
                ("Okitabojimuvexiju", True),
                ("<IsVM>b__0", True),
                ("<>c__DisplayClass0_1", True),
                ("<IsVM>b__1", True),
                ("Lysunedizov", True),
                ("Ecevygacyteti", True),
                ("Ovoresujexe", True),
                ("Fozamamigotaz", True),
                ("Egafudavudigamyse", True),
                ("<IsCIS>b__0", True),
                ("language", True),
                ("<IsCIS>b__1", True),
                ("culture", True),
                ("Tafonyhusej", True),
                ("Ihusutimucyjucyha", True),
                ("Alopigekaherasuso", True),
                ("Edyduruxifomi", True),
                ("Gexofehocil", True),
                ("Ezafivu", True),
                ("Elahamyhibipurine", True),
                ("Dibobehadamuc", True),
                ("Igibefujamexicoky", True),
                ("Ocacutajivololimy", True),
                ("Ificodacujoburebo", True),
                ("Ojolakodotuzazake", True),
                ("Ubaryzibepoxokyjo", True),
                ("Ozegoxozimatitusu", True),
                ("Voxyfenyxosupipap", True),
                ("Ixajysisibela", True),
                ("Acagelypyvolidibi", True),
                ("Ivexytudyvupucajo", True),
                ("Efagelocezyfifepi", True),
                ("Xefilesucyzukubif", True),
                ("Cojyramokixed", True),
                ("Cylelezuhevinafem", True),
                ("Gojituteriteroruj", True),
                ("Ruryryhazejib", True),
                ("Odyjituzygyluholy", True),
                ("Yxapanogirodalafi", True),
                ("Ebijosypulyrovalu", True),
                ("Yfitonyfatyfelaro", True),
                ("Nesajyvoxoxodipon", True),
                ("Inocarezusifikafu", True),
                ("Tycybolifemap", True),
                ("Gupymohylolidoken", True),
                ("Ofexebapujykovety", True),
                ("Hicycylolulyxapon", True),
                ("Vatovubinydemetex", True),
                ("Vodesemijuxivysib", True),
                ("Enuxiholodedadopo", True),
                ("Ehocojimecelehaza", True),
                ("Isohozunijaka", True),
                ("Lumytonarununuhug", True),
                ("Lijilobegofag", True),
                ("Nigozukahozasyzuz", True),
                ("Sulozofykufolydez", True),
                ("Oruxicosibino", True),
                ("Vozukufajykuporix", True),
                ("Ikyzamehypidy", True),
                ("Jijikejykyhonibax", True),
                ("Gacohetyhagakizaf", True),
                ("Dykuhilitepaxenan", True),
                ("Xexezenyhyfal", True),
                ("Mixynexinyjutabon", True),
                ("Hurocasubydumilyn", True),
                ("Ejetajykepevy", True),
                ("Jurefejipynomusyp", True),
                ("Hukahejefulen", True),
                ("Odoxebocavujybycu", True),
                ("<0>__GetDirectories", True),
                ("<>9__6_0", False),
                ("<>9__6_1", False),
                ("<>9__6_2", False),
                ("<>9__6_3", False),
                ("<ParseDiscordTokens>b__6_0", True),
                ("<ParseDiscordTokens>b__6_1", True),
                ("<ParseDiscordTokens>b__6_2", True),
                ("<ParseDiscordTokens>b__6_3", True),
                ("<>c__DisplayClass11_0", True),
                ("Xifutobykodyficom", True),
                ("<CookiesTags>b__0", True),
                ("<>c__DisplayClass12_0", True),
                ("Rokitarosomenosib", True),
                ("<PasswordsTags>b__0", True),
                ("Oninefigatelosiky", True),
                ("<ParseDiscordTokens>b__4", True),
                ("<>h__TransparentIdentifier2", True),
                ("<>c__DisplayClass7_0", True),
                ("Degajygihamejobuh", True),
                ("<ParseMasterKey>b__0", True),
                ("<>c__DisplayClass8_0", True),
                ("Hadurymuromosamom", True),
                ("<>c__DisplayClass8_1", True),
                ("Toxysotylobajamov", True),
                ("Ihiludozylejizoxy", True),
                ("<ParseDatabase>b__0", True),
                ("Cigokezideh", True),
                ("Axazuxorypike", True),
                ("Decyzakuhapuvetuv", True),
                ("Xugytukajokupucyc", True),
                ("Lakefitufesodynih", True),
                ("Alemesygulinyfygu", True),
                ("Ubazyzorazy", True),
                ("LoadLibrary", True),
                ("kernel32.dll", True),
                ("lpFileName", True),
                ("GetProcAddress", True),
                ("hModule", True),
                ("procName", True),
                ("Ydykyfupicidi", True),
                ("Podaxydexumapamax", True),
                ("Bybohugypumugujap", True),
                ("Axypinajidy", True),
                ("Mygivelerihojyl", True),
                ("ProcessName", True),
                ("Cozulutumymigiseg", True),
                ("FileName", True),
                ("Gepodaxijymosibix", True),
                ("processName", True),
                ("processID", True),
                ("fileName", True),
                ("fileHandleID", True),
                ("Vypobykikugoxek", True),
                ("Length", True),
                ("MaximumLength", True),
                ("buffer", True),
                ("Esytelajaziveli", True),
                ("ProcessId", True),
                ("ObjectTypeNumber", True),
                ("Flags", True),
                ("Fozemononyluhyrol", True),
                ("Object_Pointer", True),
                ("GrantedAccess", True),
                ("Cugugidolyzecyk", True),
                ("Name", True),
                ("Ajugikelyfozone", True),
                ("value__", True),
                ("STATUS_SUCCESS", True),
                ("STATUS_INFO_LENGTH_MISMATCH", True),
                ("STATUS_BUFFER_OVERFLOW", True),
                ("INVALID_HANDLE", True),
                ("Fekaxuguvatybez", True),
                ("PageReadonly", True),
                ("PageReadWrite", True),
                ("PageWriteCopy", True),
                ("PageExecuteRead", True),
                ("PageExecuteReadWrite", True),
                ("SectionCommit", True),
                ("SectionImage", True),
                ("SectionNoCache", True),
                ("SectionReserve", True),
                ("Zifabasyjigofip", True),
                ("FileMapCopy", True),
                ("FileMapWrite", True),
                ("FileMapRead", True),
                ("FileMapAllAccess", True),
                ("FileMapExecute", True),
                ("Gybynenimolakit", True),
                ("Disk", True),
                ("Pipe", True),
                ("Remote", True),
                ("Unknown", True),
                ("Pupobobakotolon", True),
                ("ObjectBasicInformation", True),
                ("ObjectNameInformation", True),
                ("ObjectTypeInformation", True),
                ("ObjectAllInformation", True),
                ("ObjectDataInformation", True),
                ("Loragatuvumipol", True),
                ("Terminate", True),
                ("CreateThread", True),
                ("VirtualMemoryOperation", True),
                ("VirtualMemoryRead", True),
                ("VirtualMemoryWrite", True),
                ("DuplicateHandle", True),
                ("CreateProcess", True),
                ("SetQuota", True),
                ("SetInformation", True),
                ("QueryInformation", True),
                ("QueryLimitedInformation", True),
                ("Synchronize", True),
                ("Ozatifaxukylava", True),
                ("DUPLICATE_CLOSE_SOURCE", True),
                ("DUPLICATE_SAME_ACCESS", True),
                ("Yrasuzuzorybelo", True),
                ("SystemBasicInformation", True),
                ("SystemPerformanceInformation", True),
                ("SystemTimeOfDayInformation", True),
                ("SystemProcessInformation", True),
                ("SystemProcessorPerformanceInformation", True),
                ("SystemHandleInformation", True),
                ("SystemInterruptInformation", True),
                ("SystemExceptionInformation", True),
                ("SystemRegistryQuotaInformation", True),
                ("SystemLookasideInformation", True),
                ("Ntdll", True),
                ("NtQueryObject", True),
                ("ntdll.dll", True),
                ("Handle", True),
                ("ObjectInformationClass", True),
                ("ObjectInformation", True),
                ("ObjectInformationLength", True),
                ("ReturnLength", True),
                ("NtQuerySystemInformation", True),
                ("SystemInformationClass", True),
                ("SystemInformation", True),
                ("SystemInformationLength", True),
                ("Kernel32", True),
                ("NtClose", True),
                ("hObject", True),
                ("OpenProcess", True),
                ("processAccess", True),
                ("bInheritHandle", True),
                ("processId", True),
                ("GetCurrentProcess", True),
                ("hSourceProcessHandle", True),
                ("hSourceHandle", True),
                ("hTargetProcessHandle", True),
                ("lpTargetHandle", True),
                ("dwDesiredAccess", True),
                ("options", True),
                ("QueryDosDevice", True),
                ("lpDeviceName", True),
                ("lpTargetPath", True),
            ]

        # These are the hardcoded GOOD and BAD lists used as ground truth.
        good_strings = [
            string for string, expected_good in expected_results if expected_good
        ]
        bad_strings = [
            string for string, expected_good in expected_results if not expected_good
        ]

        good_string_set = set(good_strings)
        bad_string_set = set(bad_strings)
        overlapping_labels = good_string_set & bad_string_set
        self.assertFalse(
            overlapping_labels,
            f"Strings labelled as both GOOD and BAD: {sorted(overlapping_labels)!r}",
        )

        # Require the external input file to contain exactly the labelled test
        # strings, including duplicate occurrences.
        self.assertCountEqual(
            string_list,
            [string for string, _expected_good in expected_results],
            "strings_list.txt does not match the hardcoded ground truth",
        )

        expected_by_string = {
            string: expected_good for string, expected_good in expected_results
        }

        true_good = 0
        true_bad = 0
        false_good = 0
        missed_good = 0
        false_positives: list[str] = []
        false_negatives: list[str] = []

        for string, prediction in zip(string_list, predictions, strict=True):
            expected_good = expected_by_string[string]
            predicted_good = bool(prediction)

            if expected_good and predicted_good:
                true_good += 1
            elif not expected_good and not predicted_good:
                true_bad += 1
            elif not expected_good and predicted_good:
                false_good += 1
                false_positives.append(string)
            else:
                missed_good += 1
                false_negatives.append(string)

        total = len(string_list)
        correct = true_good + true_bad
        accuracy_percent = (correct / total) * 100
        good_precision = true_good / (true_good + false_good) if true_good + false_good else 0.0
        good_recall = true_good / (true_good + missed_good) if true_good + missed_good else 0.0
        good_f1 = (
            2 * good_precision * good_recall / (good_precision + good_recall)
            if good_precision + good_recall
            else 0.0
        )

        print("\nSmartStringFilter labelled evaluation")
        print(f"Model type:          {MODEL_TYPE}")
        print(f"Labelled strings:    {total}")
        print(f"Expected GOOD:       {len(good_strings)}")
        print(f"Expected BAD:        {len(bad_strings)}")
        print(f"Correct:             {correct}")
        print(f"Incorrect:           {false_good + missed_good}")
        print(f"Accuracy:            {accuracy_percent:.2f}%")
        print(f"GOOD precision:      {good_precision * 100:.2f}%")
        print(f"GOOD recall:         {good_recall * 100:.2f}%")
        print(f"GOOD F1:             {good_f1 * 100:.2f}%")
        print(f"True GOOD:           {true_good}")
        print(f"True BAD:            {true_bad}")
        print(f"False GOOD:          {false_good}")
        print(f"Missed GOOD:         {missed_good}")

        if false_positives:
            print("\nExpected BAD but model predicted GOOD:")
            for string in false_positives:
                print(f"  {string!r}")

        if false_negatives:
            print("\nExpected GOOD but model predicted BAD:")
            for string in false_negatives:
                print(f"  {string!r}")

        self.assertGreaterEqual(
            accuracy_percent,
            MINIMUM_ACCURACY_PERCENT,
            f"Model accuracy {accuracy_percent:.2f}% is below "
            f"the required {MINIMUM_ACCURACY_PERCENT:.2f}%",
        )


if __name__ == "__main__":
    unittest.main()
